name: appsyncmasterclass
schema: schema.api.graphql
authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: eu-west-1
    defaultAction: ALLOW
    userPoolId: !Ref CognitoUserPool
resolvers:
  Query.getMyProfile:
    dataSource: usersTable
    kind: UNIT
    code: "resolvers/getMyProfile.js"

  Query.getImageUploadUrl:
    dataSource: getImageUploadUrlFunction
    kind: UNIT

  Query.getTweets:
    dataSource: tweetsTable
    kind: UNIT
    request: "mapping-templates/Query.getTweets.request.vtl"
    response: "mapping-templates/Query.getTweets.response.vtl"

  Query.getMyTimeline:
    dataSource: timelinesTable
    kind: UNIT
    request: "mapping-templates/Query.getMyTimeline.request.vtl"
    response: "mapping-templates/Query.getMyTimeline.response.vtl"

  Mutation.editMyProfile:
    dataSource: usersTable
    kind: UNIT
    code: "resolvers/editMyProfile.js"
    # request: 'mapping-templates/Mutation.editMyProfile.request.vtl'
    # response: 'mapping-templates/Mutation.editMyProfile.response.vtl'

  Mutation.tweet:
    dataSource: tweetFunction
    kind: UNIT

  Mutation.like:
    dataSource: likesSource
    kind: UNIT
    code: "resolvers/like.js"

  ## nested fields:
  Tweet.profile:
    dataSource: usersTable
    kind: UNIT
    request: "mapping-templates/Tweet.profile.request.vtl"
    response: "mapping-templates/Tweet.profile.response.vtl"

  TimelinePage.tweets:
    dataSource: tweetsTable
    kind: UNIT
    request: "mapping-templates/TimelinePage.tweets.request.vtl"
    response: "mapping-templates/TimelinePage.tweets.response.vtl"

dataSources:
  none:
    type: NONE

  usersTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref UsersTable

  tweetsTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TweetsTable

  timelinesTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TimelinesTable

  likesSource:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource: !GetAtt UsersTable.Arn
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource: !GetAtt TweetsTable.Arn

  getImageUploadUrlFunction:
    type: AWS_LAMBDA
    config:
      functionName: getImageUploadUrl

  tweetFunction:
    type: AWS_LAMBDA
    config:
      functionName: tweet

substitutions:
  TweetsTable: !Ref TweetsTable
  UsersTable: !Ref UsersTable
  LikesTable: !Ref LikesTable
