name: appsyncmasterclass
schema: schema.api.graphql
authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: eu-west-1
    defaultAction: ALLOW
    userPoolId: !Ref CognitoUserPool
resolvers:
  
  Query.getMyProfile:
    dataSource: usersTable
    kind: UNIT
    request: 'mapping-templates/Query.getMyProfile.request.vtl'
    response: 'mapping-templates/Query.getMyProfile.response.vtl'

  Query.getImageUploadUrl:
    dataSource: getImageUploadUrlFunction
    kind: UNIT
  
  Query.getTweets:
    dataSource: tweetsTable
    kind: UNIT
    request: 'mapping-templates/Query.getTweets.request.vtl'
    response: 'mapping-templates/Query.getTweets.response.vtl'
  
  Query.getMyTimeline:
    dataSource: timelinesTable
    kind: UNIT
    request: 'mapping-templates/Query.getMyTimeline.request.vtl'
    response: 'mapping-templates/Query.getMyTimeline.response.vtl'


  Mutation.editMyProfile:
    dataSource: usersTable
    kind: UNIT
    request: 'mapping-templates/Mutation.editMyProfile.request.vtl'
    response: 'mapping-templates/Mutation.editMyProfile.response.vtl'
  
  Mutation.tweet:
    dataSource: tweetFunction
    kind: UNIT


  ## nested fields:
  Tweet.profile:
    dataSource: usersTable
    kind: UNIT
    request: 'mapping-templates/Tweet.profile.request.vtl'
    response: 'mapping-templates/Tweet.profile.response.vtl'
  
  
  TimelinePage.tweets:
    dataSource: tweetsTable
    kind: UNIT
    request: 'mapping-templates/TimelinePage.tweets.request.vtl'
    response: 'mapping-templates/TimelinePage.tweets.response.vtl'
  
dataSources:

  none:
    type: NONE

  usersTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref UsersTable

  tweetsTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TweetsTable

  timelinesTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TimelinesTable

  getImageUploadUrlFunction:
    type: AWS_LAMBDA
    config:
      functionName: getImageUploadUrl

  tweetFunction:
    type: AWS_LAMBDA
    config: 
      functionName: tweet

substitutions:
  TweetsTable: !Ref TweetsTable